### ISSUE TITLE
I have few question of JPEG

### ISSUE THREAD

**Issue by HanalogInstruments** [dannye/jed#1]
Hi,
Some jpeg corrupted header and SOI too, can i read the raw data without header from reference jpeg to repair corrupted jpeg?
i saw a guy using this method:
https://www.jpegmedic.com/tools/jpegmedic-arwe/

**Comment by dannye** [comment]
I don't understand your question. You are asking me if you can do something? That is a question for you to answer.
If you're asking me if your idea is possible, it clearly is. You linked to an example of it being done.

**Comment by HanalogInstruments** [comment]
> I don't understand your question. You are asking me if you can do something? That is a question for you to answer.
> 
> If you're asking me if your idea is possible, it clearly is. You linked to an example of it being done.

Ah i mean can we read raw data after SOI and create new header using DQT tables,... to make jpeg working?

**Comment by dannye** [comment]
My answer is the same as before.
