### ISSUE TITLE
Memory allocation error

### ISSUE THREAD

**Issue by chan233** [dannye/jed#7]
When reading a BMP file, a security check for the image's width and height was not performed

This is the file that caused the crash:
[crash1.zip](https://github.com/user-attachments/files/16143643/crash1.zip)

```
unzip crash1.zip 
encoder crash1.bmp
```

output >>
```
Reading crash1.bmp...
Killed
```

Using GDB for debugging,:
```
gdb --args bin/encoder crash1.bmp
# The breakpoint is set at encoder.cpp:52 and  encoder.cpp:72
b 52
b 72 
r
# shows
if (getShort(inFile) != 1) {

p image.width
# shows:
$5 = 65285
# shows:
p image.height
$6 = 1535

# then continue ,  leading to an overflow when requesting a block at encoder.cpp:72.
c
p image.blockHeight
# shows:
$3 = 192
p image.blockWidth
# shows:
$4 = 8161

# then next step with:
n 
# The specific line causing the crash is: 
image.blocks = new (std::nothrow) Block[image.blockHeight * image.blockWidth]; 
```

**Comment by dannye** [comment]
The program exits correctly for me:

```
$ ./bin/encoder crash1.bmp
Reading crash1.bmp...
Writing crash1.jpg...
```

The input file also looks OK. There's no reason the input file should be rejected or cause a crash.

If the system can't allocate enough memory for a large image, then I'm okay with the program aborting.

**Comment by chan233** [comment]
Here are the basic configurations of my operating system:
```
OS: Ubuntu 22.04.4 LTS x86_64
Kernel: 5.15.0-106-generic
Resolution: 1024x768
CPU: Intel Xeon Platinum (2) @ 2.499GHz
GPU: 00:02.0 Cirrus Logic GD 5446
Memory: 886MiB / 1673MiB
```
Theoretically, allocating 
`new (std::nothrow) Block[192 * 8161]`
 should not exceed the virtual memory allocation, but you might still want to perform some conditional checks before allocating memory. Just a suggestion~

**Comment by chan233** [comment]
> The program exits correctly for me:
> 
> ```
> $ ./bin/encoder crash1.bmp
> Reading crash1.bmp...
> Writing crash1.jpg...
> ```
> 
> The input file also looks OK. There's no reason the input file should be rejected or cause a crash.
> 
> If the system can't allocate enough memory for a large image, then I'm okay with the program aborting.

Here are the basic configurations of my operating system:
```
OS: Ubuntu 22.04.4 LTS x86_64
Kernel: 5.15.0-106-generic
Resolution: 1024x768
CPU: Intel Xeon Platinum (2) @ 2.499GHz
GPU: 00:02.0 Cirrus Logic GD 5446
Memory: 886MiB / 1673MiB
```
Theoretically, allocating 
`new (std::nothrow) Block[192 * 8161]`
 should not exceed the virtual memory allocation, but you might still want to perform some conditional checks before allocating memory. Just a suggestion~

**Comment by chan233** [comment]
> The program exits correctly for me:
> 
> ```
> $ ./bin/encoder crash1.bmp
> Reading crash1.bmp...
> Writing crash1.jpg...
> ```
> 
> The input file also looks OK. There's no reason the input file should be rejected or cause a crash.
> 
> If the system can't allocate enough memory for a large image, then I'm okay with the program aborting.

Here are the basic configurations of my operating system:
```
OS: Ubuntu 22.04.4 LTS x86_64
Kernel: 5.15.0-106-generic
Resolution: 1024x768
CPU: Intel Xeon Platinum (2) @ 2.499GHz
GPU: 00:02.0 Cirrus Logic GD 5446
Memory: 886MiB / 1673MiB
```
Theoretically, allocating 
`new (std::nothrow) Block[192 * 8161]`
 should not exceed the virtual memory allocation, but you might still want to perform some conditional checks before allocating memory. Just a suggestion~
